# Generated by Django 4.1 on 2022-09-03 09:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
